Removed dduper for btrfs utils due to build err
```
error: builder for '/nix/store/9xxsmzb0z9f4xlpblhmzyrl5xf71kpv2-btrfs-progs-6.3.3.drv' failed with exit code 2;
       last 10 log lines:
       > cmds/inspect-dump-csum.c:214:41: warning: excess elements in struct initializer
       >   214 |         struct open_ctree_flags ocf = { 0 };
       >       |                                         ^
       > cmds/inspect-dump-csum.c:214:41: note: (near initialization for 'ocf')
       > cmds/inspect-dump-csum.c:214:33: error: storage size of 'ocf' isn't known
       >   214 |         struct open_ctree_flags ocf = { 0 };
       >       |                                 ^~~
       > cmds/inspect-dump-csum.c:214:33: warning: unused variable 'ocf' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-variable-Wunused-variable8;;]
       > make: *** [Makefile:456: cmds/inspect-dump-csum.o] Error 1
       > make: *** Waiting for unfinished jobs....
       For full logs, run 'nix log /nix/store/9xxsmzb0z9f4xlpblhmzyrl5xf71kpv2-btrfs-progs-6.3.3.drv'.
error: 1 dependencies of derivation '/nix/store/dmy884flsykxp90ljfqyl5s3544h69l1-dduper-0.04.drv' failed to build
error: 1 dependencies of derivation '/nix/store/74cgin3l5qk7134h33vi8qpnzbq9kbyz-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wbc3nczk8i07xddyiqz6y91idi5d1zxl-nixos-system-soma-23.11.20230821.91a22f7.drv' failed to build
```